// AUTO-GENERATED by scripts/generate-demo-audio.mjs — do not edit by hand.
// Exact cue timings measured from the stitched ElevenLabs demo MP3s so the
// transcript reveal syncs to real audio. Regenerate with:
//   node scripts/generate-demo-audio.mjs
// If the MP3s are missing at runtime, useCallPlayback falls back to a
// reading-pace timer over these same cues (transcript-only) — still animates.

import type { Cue } from "./useCallPlayback";

export const RECEPTIONIST_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 10.45, text: "Good evening, you've reached Harbourline Plumbing's assistant — just letting you know this call's recorded for training purposes; if you'd rather it wasn't, just say so. Now, what's going on tonight?" },
  { speaker: "caller", startSec: 10.75, dur: 7.62, text: "Yeah, hi — I've got a tap under the kitchen sink that's leaking, and it's sort of getting worse. There's water pooling in the cupboard now." },
  { speaker: "ai", startSec: 18.67, dur: 8.35, text: "Okay, water in the cupboard — let's sort that. First things, have you been able to shut the water off to it, or is it still running?" },
  { speaker: "caller", startSec: 27.31, dur: 6.08, text: "Ah — there's a little valve under there, I think I turned it. It's slowed right down but it's still dripping." },
  { speaker: "ai", startSec: 33.7, dur: 6.46, text: "Good on you, that's exactly the right move. Let me take some notes down for the plumber — which suburb are you in?" },
  { speaker: "caller", startSec: 40.45, dur: 1.02, text: "Marrickville." },
  { speaker: "ai", startSec: 41.77, dur: 3.11, text: "Beautiful, we cover Marrickville. And the address there?" },
  { speaker: "caller", startSec: 45.19, dur: 2.14, text: "Unit two, fourteen Station Street." },
  { speaker: "ai", startSec: 47.62, dur: 4.88, text: "Unit two, fourteen Station Street, Marrickville — got it. And your name and best number?" },
  { speaker: "caller", startSec: 52.8, dur: 4.74, text: "It's Dave — oh four nine one… five seven oh… one five six." },
  { speaker: "ai", startSec: 57.83, dur: 6.64, text: "Thanks. Just confirming — oh four nine one, five seven oh, one five six is the right number for the confirmation text?" },
  { speaker: "caller", startSec: 64.78, dur: 1.44, text: "Yep, that's the one." },
  { speaker: "ai", startSec: 66.52, dur: 6.32, text: "Perfect. One more for the notes — is it a mixer tap, the single-lever type, or separate hot and cold?" },
  { speaker: "caller", startSec: 73.13, dur: 1.86, text: "The mixer type — one lever." },
  { speaker: "ai", startSec: 75.29, dur: 10.53, text: "Mixer, noted. So you know what to expect, the call-out starts from a hundred and twenty dollars, and you get an exact quote before any work starts — no surprises." },
  { speaker: "caller", startSec: 86.22, dur: 4.83, text: "Hmm — a hundred and twenty just to come out? That's a bit steep for a tap, isn't it?" },
  { speaker: "ai", startSec: 91.35, dur: 13.84, text: "Fair question. That covers a licensed plumber coming to you with the gear and common parts already on the van — and if you go ahead with the job, it comes off the final price. No hidden extras, you'll see everything before you say yes." },
  { speaker: "caller", startSec: 105.49, dur: 1.95, text: "Righto — that's fair enough, actually." },
  { speaker: "ai", startSec: 107.74, dur: 3.39, text: "I can get someone out first thing — does eight in the morning suit?" },
  { speaker: "caller", startSec: 111.43, dur: 3.2, text: "Eight's perfect, yeah. That'd be a big relief, honestly." },
  { speaker: "ai", startSec: 115.13, dur: 4.27, text: "Done — you're booked for eight tomorrow morning. I'll text the confirmation now." },
  { speaker: "ai", startSec: 119.71, dur: 6.59, text: "And I'll send these notes through to the assigned plumber who'll be visiting you — so he knows exactly what he's walking into." },
  { speaker: "caller", startSec: 126.6, dur: 2.23, text: "Ah, brilliant. Thanks so much for that." },
  { speaker: "ai", startSec: 129.13, dur: 5.34, text: "No worries at all, Dave. Keep that valve turned down and we'll see you in the morning. Night now." },
];

export const SPEEDTOLEAD_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 13.33, text: "Hi, it's the assistant from Harbourline Plumbing — quick heads-up, this call's recorded for training purposes; happy to switch that off if you'd prefer. You just sent through a request for gutter cleaning on a two-storey in Parramatta?" },
  { speaker: "caller", startSec: 13.63, dur: 3.95, text: "Oh — wow, that was fast. I literally just hit submit." },
  { speaker: "ai", startSec: 17.88, dur: 8.17, text: "We like to be quick! Just a couple of things so we can quote it properly. Is there safe ladder access, or anything tricky like a steep pitch?" },
  { speaker: "caller", startSec: 26.35, dur: 4.55, text: "Nah, access is fine. There's a bit of a slope out the back but nothing mad." },
  { speaker: "ai", startSec: 31.2, dur: 3.89, text: "Righto — And roughly how long since they were last done?" },
  { speaker: "caller", startSec: 35.39, dur: 3.39, text: "Ooh — probably a good two years. They're pretty full." },
  { speaker: "ai", startSec: 39.08, dur: 7.89, text: "No dramas, common this time of year. And is it gutters only, or want the downpipes flushed as well? I'll pop it in the notes." },
  { speaker: "caller", startSec: 47.28, dur: 2.51, text: "Ah — may as well do the downpipes too." },
  { speaker: "caller", startSec: 50.18, dur: 3.48, text: "Actually, hang on — is this one of those AI callers?" },
  { speaker: "ai", startSec: 53.97, dur: 10.68, text: "It is — I'm Harbourline's assistant, so no enquiry sits waiting while the team's up a ladder. Everything you tell me goes straight to the crew, and a real plumber does the work. Fair enough?" },
  { speaker: "caller", startSec: 64.95, dur: 1.49, text: "Huh — fair enough, yeah." },
  { speaker: "ai", startSec: 66.73, dur: 3.44, text: "I've got Thursday morning or Friday afternoon — which works better?" },
  { speaker: "caller", startSec: 70.47, dur: 1.58, text: "Friday arvo would be good." },
  { speaker: "ai", startSec: 72.35, dur: 4.6, text: "Locked in for Friday afternoon. And the address, so the crew knows where they're headed?" },
  { speaker: "caller", startSec: 77.25, dur: 1.86, text: "Twenty-two Beech Street, Parramatta." },
  { speaker: "ai", startSec: 79.4, dur: 8.03, text: "Twenty-two Beech Street — got it. And I've got your mobile from the form, ending one five six — best number for the confirmation text?" },
  { speaker: "caller", startSec: 87.74, dur: 1.02, text: "Yep, that's me." },
  { speaker: "ai", startSec: 89.06, dur: 6.36, text: "Perfect. I'll text the confirmation now and send these notes to the assigned plumber who'll be visiting you. Talk soon." },
  { speaker: "caller", startSec: 95.72, dur: 1.11, text: "Great, thanks!" },
];

export const ADVANCED_STRATA_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 9.24, text: "Good evening, you've reached Advanced Strata's assistant — quick heads up, this call's recorded for training; if you'd rather it wasn't, just let me know. What can I help with?" },
  { speaker: "caller", startSec: 9.54, dur: 11.33, text: "Yeah, hi — so, um, I'm buying my first apartment down in Wollongong, and the agent said I need a strata report before I sign. I'll be honest, I don't really know what that is." },
  { speaker: "ai", startSec: 21.17, dur: 18.25, text: "You're in the right place — that's exactly what we do. In plain terms it's a health check on the building before you buy: the finances, any special levies coming up, past defects and repairs, the by-laws and insurance — so you know what you're walking into. Have you got a deadline you're working to?" },
  { speaker: "caller", startSec: 39.72, dur: 4.74, text: "Oh — right, okay. Yeah, my cooling-off ends Thursday, so it's pretty tight." },
  { speaker: "ai", startSec: 44.76, dur: 9.1, text: "Thursday's doable — for that we'd do the urgent report: three hundred and sixty dollars plus GST, back within forty-eight hours. Can I grab the property address?" },
  { speaker: "caller", startSec: 54.16, dur: 3.85, text: "Yeah, it's, um — unit five, twelve Corrimal Street, Wollongong." },
  { speaker: "ai", startSec: 58.32, dur: 7.57, text: "Unit five, twelve Corrimal Street — got it. Do you have the strata plan number? It's on the contract, usually starts with S-P." },
  { speaker: "caller", startSec: 66.19, dur: 3.02, text: "Ahh — I don't think I've got that in front of me, sorry." },
  { speaker: "ai", startSec: 69.51, dur: 5.71, text: "No stress at all — we can pull that from the address on our end. One less thing for you to chase down." },
  { speaker: "caller", startSec: 75.52, dur: 7.43, text: "Oh, good. Um — can I ask, the agent mentioned there might be a special levy coming up. Is that something you'd pick up?" },
  { speaker: "ai", startSec: 83.25, dur: 14.02, text: "Good question — I can't put a figure on that myself, but it's exactly what the report digs into. I'll flag it so the inspector checks the meeting minutes and the building's finances for anything coming up, and Matthew can walk you through what he finds." },
  { speaker: "caller", startSec: 97.57, dur: 1.81, text: "Yeah — that'd be great, thanks." },
  { speaker: "ai", startSec: 99.68, dur: 3.85, text: "Easy. And your name and the best number for the confirmation text?" },
  { speaker: "caller", startSec: 103.84, dur: 3.9, text: "Daniel — oh four nine one, five seven oh, one five seven." },
  { speaker: "ai", startSec: 108.04, dur: 5.43, text: "Perfect, Daniel — and that's oh four nine one, five seven oh, one five seven?" },
  { speaker: "caller", startSec: 113.77, dur: 0.6, text: "That's it." },
  { speaker: "ai", startSec: 114.68, dur: 12.07, text: "Beautiful. I've marked your Thursday deadline as priority and noted the levy question for the inspector. You'll get a text with the order link now, and I'll send all of this to Matthew so he can book the inspection first thing." },
  { speaker: "caller", startSec: 127.05, dur: 4.64, text: "Honestly — that was so much easier than I expected. Thanks so much." },
  { speaker: "ai", startSec: 132.2, dur: 4.41, text: "My pleasure. Good luck with the apartment — we'll be in touch soon. Bye now." },
];

// Advanced Strata — Speed-to-Lead upsell demo.
// Per-line MiniMax TTS (MuAPI) stitched by scripts/generate-minimax-audio.mjs.
// Voices differ from the receptionist demo by design (dialogue endpoint was down).
// Cues are EXACT — measured per clip with ffprobe plus the inter-line gaps.
export const AS_SPEEDTOLEAD_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 18.1, text: "Hi, it's the assistant from Advanced Strata — you just popped in an enquiry on our site about a strata report. Quick heads up, this call's recorded for training; happy to switch that off if you'd prefer. Have I caught you at an okay time?" },
  { speaker: "caller", startSec: 18.65, dur: 4.44, text: "Oh — wow, that was quick. I literally just submitted the form." },
  { speaker: "ai", startSec: 23.38, dur: 8.7, text: "We like to be quick — the sooner we get your report moving, the better, especially if there's a deadline. Which property's it for?" },
  { speaker: "caller", startSec: 32.38, dur: 4.34, text: "Yeah, um — it's an apartment in Wollongong I'm looking at buying." },
  { speaker: "ai", startSec: 37.02, dur: 4.47, text: "Lovely. And is there a cooling-off date you're working towards?" },
  { speaker: "caller", startSec: 41.79, dur: 3.15, text: "Yeah, it ends Friday, so it's a bit tight." },
  { speaker: "ai", startSec: 45.23, dur: 12.97, text: "Friday's doable — for that we'd do the urgent report: three hundred and sixty dollars plus GST, back within forty-eight hours. Did the agent give you a strata plan number, or just the address?" },
  { speaker: "caller", startSec: 58.5, dur: 3.83, text: "Ah — just the address, I think. I don't have a plan number on me." },
  { speaker: "ai", startSec: 62.63, dur: 4.77, text: "No problem at all — we can pull that from the address. What's the address?" },
  { speaker: "caller", startSec: 67.71, dur: 3.88, text: "It's unit eight, forty Crown Street, Wollongong." },
  { speaker: "ai", startSec: 71.88, dur: 16.29, text: "Unit eight, forty Crown Street — got it. I'll text you the order link now so you can lock it in, and I'll flag your Friday deadline as priority for Matthew. Is this the best number for the text — the one you're on?" },
  { speaker: "caller", startSec: 88.47, dur: 1.57, text: "Yeah, this one's good." },
  { speaker: "ai", startSec: 90.34, dur: 9.72, text: "Perfect. You'll have the link in a moment, and Matthew will make sure the inspection's booked in time for Friday. Anything else I can help with?" },
  { speaker: "caller", startSec: 100.36, dur: 3.96, text: "No, that's great — honestly, that was so easy. Thanks so much." },
  { speaker: "ai", startSec: 104.62, dur: 4.39, text: "My pleasure. Good luck with the apartment — bye for now." },
];

