// AUTO-GENERATED by scripts/generate-demo-audio.mjs — do not edit by hand.
// Exact cue timings measured from the stitched ElevenLabs demo MP3s so the
// transcript reveal syncs to real audio. Regenerate with:
//   node scripts/generate-demo-audio.mjs
// If the MP3s are missing at runtime, useCallPlayback falls back to a
// reading-pace timer over these same cues (transcript-only) — still animates.

import type { Cue } from "./useCallPlayback";

export const RECEPTIONIST_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 7.71, text: "Good evening, you've reached Harbourline Plumbing's after-hours assistant. I can take your details and get you booked in — what's going on tonight?" },
  { speaker: "caller", startSec: 8.01, dur: 7.62, text: "Yeah, hi — I've got a tap under the kitchen sink that's leaking, and it's sort of getting worse. There's water pooling in the cupboard now." },
  { speaker: "ai", startSec: 15.93, dur: 8.35, text: "Okay, water in the cupboard — let's sort that. First things, have you been able to shut the water off to it, or is it still running?" },
  { speaker: "caller", startSec: 24.57, dur: 6.08, text: "Ah — there's a little valve under there, I think I turned it. It's slowed right down but it's still dripping." },
  { speaker: "ai", startSec: 30.96, dur: 6.78, text: "Good on you, that's exactly the right move — that'll keep the damage down overnight. Whereabouts are you? Which suburb?" },
  { speaker: "caller", startSec: 38.04, dur: 1.02, text: "Marrickville." },
  { speaker: "ai", startSec: 39.36, dur: 4.97, text: "Beautiful, we cover Marrickville. Can I grab your name and the best number to reach you on?" },
  { speaker: "caller", startSec: 44.63, dur: 3.44, text: "It's Dave — 0400 123 456." },
  { speaker: "ai", startSec: 48.36, dur: 10.53, text: "Thanks Dave. So you know what to expect, our call-out starts from $120, and the plumber gives you an exact quote once he's had a look — no surprises." },
  { speaker: "caller", startSec: 59.2, dur: 1.25, text: "Yeah, that's fine." },
  { speaker: "ai", startSec: 60.75, dur: 4.6, text: "Easy. I can get someone out to you first thing — does eight in the morning suit?" },
  { speaker: "caller", startSec: 65.65, dur: 3.2, text: "Eight's perfect, yeah. That'd be a big relief, honestly." },
  { speaker: "ai", startSec: 69.35, dur: 8.59, text: "Done — you're booked for 8am. I'll text you a confirmation with all the details in just a moment, and the owner gets a summary of this tonight, so it's all in hand." },
  { speaker: "caller", startSec: 78.24, dur: 2.23, text: "Ah, brilliant. Thanks so much for that." },
  { speaker: "ai", startSec: 80.77, dur: 5.34, text: "No worries at all, Dave. Keep that valve turned down and we'll see you in the morning. Night now." },
];

export const SPEEDTOLEAD_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 9.1, text: "Hi, this is the assistant from Harbourline Plumbing — you just popped in a request for gutter cleaning on a two-storey in Parramatta. Have I caught you at an okay time?" },
  { speaker: "caller", startSec: 9.4, dur: 3.95, text: "Oh — wow, that was fast. I literally just hit submit." },
  { speaker: "ai", startSec: 13.65, dur: 9.33, text: "We like to be quick! Just a couple of things so we can quote it properly. Is there safe ladder access around the place, or anything tricky like a steep pitch?" },
  { speaker: "caller", startSec: 23.28, dur: 4.55, text: "Nah, access is fine. There's a bit of a slope out the back but nothing mad." },
  { speaker: "ai", startSec: 28.14, dur: 3.75, text: "Perfect. And roughly how long since they were last done?" },
  { speaker: "caller", startSec: 32.19, dur: 3.39, text: "Ooh — probably a good two years. They're pretty full." },
  { speaker: "ai", startSec: 35.88, dur: 7.57, text: "No dramas, that's a common one this time of year. I've got a spot Thursday morning or Friday afternoon — which works better for you?" },
  { speaker: "caller", startSec: 43.75, dur: 1.58, text: "Friday arvo would be good." },
  { speaker: "ai", startSec: 45.62, dur: 7.24, text: "Locked in for Friday afternoon. I'll shoot you a text now with the confirmation and what to expect. Thanks for that — talk soon." },
  { speaker: "caller", startSec: 53.17, dur: 1.11, text: "Great, thanks!" },
];
