// AUTO-GENERATED by scripts/generate-demo-audio.mjs — do not edit by hand.
// Exact cue timings measured from the stitched ElevenLabs demo MP3s so the
// transcript reveal syncs to real audio. Regenerate with:
//   node scripts/generate-demo-audio.mjs
// If the MP3s are missing at runtime, useCallPlayback falls back to a
// reading-pace timer over these same cues (transcript-only) — still animates.

import type { Cue } from "./useCallPlayback";

export const RECEPTIONIST_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 10.45, text: "Good evening, you've reached Harbourline Plumbing's assistant — just letting you know this call's recorded for training purposes; if you'd rather it wasn't, just say so. Now, what's going on tonight?" },
  { speaker: "caller", startSec: 10.75, dur: 7.62, text: "Yeah, hi — I've got a tap under the kitchen sink that's leaking, and it's sort of getting worse. There's water pooling in the cupboard now." },
  { speaker: "ai", startSec: 18.67, dur: 8.35, text: "Okay, water in the cupboard — let's sort that. First things, have you been able to shut the water off to it, or is it still running?" },
  { speaker: "caller", startSec: 27.31, dur: 6.08, text: "Ah — there's a little valve under there, I think I turned it. It's slowed right down but it's still dripping." },
  { speaker: "ai", startSec: 33.7, dur: 6.46, text: "Good on you, that's exactly the right move. Let me take some notes down for the plumber — which suburb are you in?" },
  { speaker: "caller", startSec: 40.45, dur: 1.02, text: "Marrickville." },
  { speaker: "ai", startSec: 41.77, dur: 3.11, text: "Beautiful, we cover Marrickville. And the address there?" },
  { speaker: "caller", startSec: 45.19, dur: 2.14, text: "Unit two, fourteen Station Street." },
  { speaker: "ai", startSec: 47.62, dur: 4.88, text: "Unit two, fourteen Station Street, Marrickville — got it. And your name and best number?" },
  { speaker: "caller", startSec: 52.8, dur: 4.74, text: "It's Dave — oh four nine one… five seven oh… one five six." },
  { speaker: "ai", startSec: 57.83, dur: 6.64, text: "Thanks. Just confirming — oh four nine one, five seven oh, one five six is the right number for the confirmation text?" },
  { speaker: "caller", startSec: 64.78, dur: 1.44, text: "Yep, that's the one." },
  { speaker: "ai", startSec: 66.52, dur: 6.32, text: "Perfect. One more for the notes — is it a mixer tap, the single-lever type, or separate hot and cold?" },
  { speaker: "caller", startSec: 73.13, dur: 1.86, text: "The mixer type — one lever." },
  { speaker: "ai", startSec: 75.29, dur: 10.53, text: "Mixer, noted. So you know what to expect, the call-out starts from a hundred and twenty dollars, and you get an exact quote before any work starts — no surprises." },
  { speaker: "caller", startSec: 86.22, dur: 4.83, text: "Hmm — a hundred and twenty just to come out? That's a bit steep for a tap, isn't it?" },
  { speaker: "ai", startSec: 91.35, dur: 13.84, text: "Fair question. That covers a licensed plumber coming to you with the gear and common parts already on the van — and if you go ahead with the job, it comes off the final price. No hidden extras, you'll see everything before you say yes." },
  { speaker: "caller", startSec: 105.49, dur: 1.95, text: "Righto — that's fair enough, actually." },
  { speaker: "ai", startSec: 107.74, dur: 3.39, text: "I can get someone out first thing — does eight in the morning suit?" },
  { speaker: "caller", startSec: 111.43, dur: 3.2, text: "Eight's perfect, yeah. That'd be a big relief, honestly." },
  { speaker: "ai", startSec: 115.13, dur: 4.27, text: "Done — you're booked for eight tomorrow morning. I'll text the confirmation now." },
  { speaker: "ai", startSec: 119.71, dur: 6.59, text: "And I'll send these notes through to the assigned plumber who'll be visiting you — so he knows exactly what he's walking into." },
  { speaker: "caller", startSec: 126.6, dur: 2.23, text: "Ah, brilliant. Thanks so much for that." },
  { speaker: "ai", startSec: 129.13, dur: 5.34, text: "No worries at all, Dave. Keep that valve turned down and we'll see you in the morning. Night now." },
];

export const SPEEDTOLEAD_CUES: Cue[] = [
  { speaker: "ai", startSec: 0, dur: 13.33, text: "Hi, it's the assistant from Harbourline Plumbing — quick heads-up, this call's recorded for training purposes; happy to switch that off if you'd prefer. You just sent through a request for gutter cleaning on a two-storey in Parramatta?" },
  { speaker: "caller", startSec: 13.63, dur: 3.95, text: "Oh — wow, that was fast. I literally just hit submit." },
  { speaker: "ai", startSec: 17.88, dur: 8.17, text: "We like to be quick! Just a couple of things so we can quote it properly. Is there safe ladder access, or anything tricky like a steep pitch?" },
  { speaker: "caller", startSec: 26.35, dur: 4.55, text: "Nah, access is fine. There's a bit of a slope out the back but nothing mad." },
  { speaker: "ai", startSec: 31.2, dur: 3.89, text: "Righto — And roughly how long since they were last done?" },
  { speaker: "caller", startSec: 35.39, dur: 3.39, text: "Ooh — probably a good two years. They're pretty full." },
  { speaker: "ai", startSec: 39.08, dur: 7.89, text: "No dramas, common this time of year. And is it gutters only, or want the downpipes flushed as well? I'll pop it in the notes." },
  { speaker: "caller", startSec: 47.28, dur: 2.51, text: "Ah — may as well do the downpipes too." },
  { speaker: "caller", startSec: 50.18, dur: 3.48, text: "Actually, hang on — is this one of those AI callers?" },
  { speaker: "ai", startSec: 53.97, dur: 10.68, text: "It is — I'm Harbourline's assistant, so no enquiry sits waiting while the team's up a ladder. Everything you tell me goes straight to the crew, and a real plumber does the work. Fair enough?" },
  { speaker: "caller", startSec: 64.95, dur: 1.49, text: "Huh — fair enough, yeah." },
  { speaker: "ai", startSec: 66.73, dur: 3.44, text: "I've got Thursday morning or Friday afternoon — which works better?" },
  { speaker: "caller", startSec: 70.47, dur: 1.58, text: "Friday arvo would be good." },
  { speaker: "ai", startSec: 72.35, dur: 4.6, text: "Locked in for Friday afternoon. And the address, so the crew knows where they're headed?" },
  { speaker: "caller", startSec: 77.25, dur: 1.86, text: "Twenty-two Beech Street, Parramatta." },
  { speaker: "ai", startSec: 79.4, dur: 8.03, text: "Twenty-two Beech Street — got it. And I've got your mobile from the form, ending one five six — best number for the confirmation text?" },
  { speaker: "caller", startSec: 87.74, dur: 1.02, text: "Yep, that's me." },
  { speaker: "ai", startSec: 89.06, dur: 6.36, text: "Perfect. I'll text the confirmation now and send these notes to the assigned plumber who'll be visiting you. Talk soon." },
  { speaker: "caller", startSec: 95.72, dur: 1.11, text: "Great, thanks!" },
];
